# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "test", "main" ]

  workflow_dispatch:

jobs:
  get-deploy-env:
    runs-on: ubuntu-latest
    outputs:
      deploy_env: ${{ steps.get_name.outputs.name }}
    steps:
      - name: Define environment name
        id: get_name
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            ENV_NAME=Production
          elif [[ "${{ github.ref }}" == "refs/heads/test" ]]; then
            ENV_NAME=Staging
          else
            exit 1
          fi
          echo    "ENV_NAME_TEST=$ENV_NAME" >> $GITHUB_ENV
          echo    "name=$ENV_NAME" >> $GITHUB_OUTPUT
      - name: Print woup
        run: echo $ENV_NAME
      - name: Print truc
        run: echo $ENV_NAME_TEST


  deploy-to:
    runs-on: ubuntu-latest
    needs:
      - get-deploy-env
    environment:
      name: ${{ needs.get-deploy-env.outputs.deploy_env }}
      url: ${{ vars.ENV_URL }}
    steps:
      # Runs a single command using the runners shell
      - name: Do something to deploy
        run: echo Deploy
