# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "test", "main" ]

env:
  ENV_NAME: ${{ github.ref == 'refs/heads/main' && 'Production' || 'Staging' }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: ${{ env.ENV_NAME }}
      url: ${{ vars.ENV_URL }}
    steps:
      # Runs a single command using the runners shell
      - name: Do something to deploy
        run: echo Deploy
